### ISSUE TITLE
Playlist Bug

### ISSUE THREAD

**Issue by iddu0** [Iemand005/FoxMusic#1]
### iOS 6 iPod Touch 4th Gen
Playlists are not loading, but the search feature is is. 
Thanks for the awesome app!

**Comment by Iemand005** [comment]
Some playlists indeed don't load, I haven't looked into why yet. I will dig into it later. The app is far from done I will fix and improve it when I'm done doing internship.
Thanks for reminding me!

**Comment by iddu0** [comment]
Yw!

**Comment by Iemand005** [comment]
@iddu0 I am now restarting development of the app, already fixed some bugs. The playlists load for me. Just to let you know, the playlists that should show up in the app are the ones you added in Spotify web or something else, I will add playlist searching, adding and other features directly into the app soon.

**Comment by iddu0** [comment]
OK. 
`the playlists that should show up in the app are the ones you added in Spotify web or something else`
I must have done something wrong.
